version: '3.3'

services:
  books_of_my_life:
    image: books_of_my_life_backend
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3307
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: books_of_my_life_development
      WAIT_HOSTS: db:3306
    ports:
      - '5000:5000'
      - '9229:9229'
    command: sh -c "/wait && npm run migrate && npm run dev"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: books_of_my_life_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: books_of_my_life
      MYSQL_USER: manager
      MYSQL_PASSWORD: manager
    ports:
      - "3307:3306"
