version: '3.7'

services:
  books_of_my_life:
    image: books_of_my_life_backend
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: test
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: books_of_my_life_test
      WAIT_HOSTS: db:5432
    ports:
      - '5000:5000'
      - '9229:9229'
    command: sh -c "/wait && npm run migrate && npm t"
    depends_on:
      - db
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_of_my_life_test
